FROM golang:latest as build

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -o /main ./ReceiptWebService
 
FROM ubuntu:latest as run

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates sqlite3 libsqlite3-0 && \
    rm -rf /var/lib/apt/lists/*

# Copy the application executable from the build image
COPY --from=build /main /main

EXPOSE 8080

CMD ["./main"]